"""
codegen.py - CHIP-8 and Super-CHIP Code Generator for Flashiibo FEB SDK.
"""

import re


class CodeGenerator:
    """Emits optimized CHIP-8 assembly from a parsed AST."""
    def __init__(self, ast_data, macros=None):
        self.globals = ast_data["globals"]
        self.functions = ast_data["functions"]
        self.strings = ast_data["strings"]
        self.struct_types = ast_data["struct_types"]
        self.macros = macros or {}

        self.label_counter = 0
        self.frame_buffers = set()
        self.call_arg_buffers = set()
        self.needs_mul = False
        self.needs_div = False
        self.needs_mod = False

    def new_label(self, prefix="L"):
        self.label_counter += 1
        return f"{prefix}_{self.label_counter}"

    def generate(self):
        return self.generate_assembly()

    def generate_assembly(self):
        out = []
        out.append(";;; ===========================================================================")
        out.append(";;; Flashiibo FEB Bytecode (Generated by c_compiler.py)")
        out.append(";;; Target: Flashiibo Gen3 Super-CHIP (128x64 display, 4-button hardware)")
        out.append(";;; ===========================================================================")
        out.append("")
        out.append("START:")
        out.append("        call MAIN")
        out.append("        exit")
        out.append("")

        # Compile each function
        for func_name, func_data in self.functions.items():
            self.compile_function(func_name, func_data, out)

        # Emit string literals
        if self.strings:
            out.append(";;; String Literals")
            for text, label in self.strings.items():
                escaped = text.replace('"', '\\"')
                out.append(f"{label}:")
                out.append(f'        .asciz "{escaped}"')
            out.append("")

        # Function local call frames
        if self.frame_buffers:
            out.append(";;; Function Local Call Frames")
            for fname in sorted(self.frame_buffers):
                out.append(f"FRAME_{fname.upper()}:")
                out.append("        .ds 16")
            out.append("")

        # Call argument scratch buffers
        if self.call_arg_buffers:
            out.append(";;; Call Argument Scratch Buffers")
            for bname in sorted(self.call_arg_buffers):
                out.append(f"{bname}:")
                out.append("        .byte 0x00")
            out.append("")

        # Emit globals
        if self.globals:
            out.append(";;; Global Variables and Memory Tables")
            for name, g in self.globals.items():
                label = name.upper()
                out.append(f"{label}:")
                if g["type"] == "array":
                    vals = g["values"]
                    if vals:
                        # Chunk into lines of 16 bytes max
                        for i in range(0, len(vals), 16):
                            chunk = vals[i:i + 16]
                            byte_strs = [f"0x{b & 0xFF:02x}" for b in chunk]
                            out.append("        .byte " + ", ".join(byte_strs))
                    else:
                        out.append(f"        .ds {g['size']}")
                elif g["type"] == "struct":
                    out.append(f"        .ds {g['size']}")
                else:
                    out.append(f"        .byte 0x{g['value'] & 0xFF:02x}")
            out.append("")

        # Emit runtime math helpers if needed (using only scratch registers v0, va, vb, vc, vd, ve, vf)
        if self.needs_mul:
            out.append(""";;; 8-Bit Software Multiplication Helper
__MUL8:
        load v0, 0
        load vc, 1
__MUL8_LOOP:
        skip.ne vb, 0
        ret
        load ve, vb
        and ve, vc
        skip.eq ve, 0
        add v0, va
        add va, va
        shr vb
        jump __MUL8_LOOP
""")
        if self.needs_div or self.needs_mod:
            out.append(""";;; 8-Bit Software Division & Modulo Helper
__DIVMOD8:
        load v0, 0
        load vd, 0
        load vc, 128
__DIVMOD8_LOOP:
        add v0, v0
        add vd, vd
        load ve, va
        and ve, vc
        skip.eq ve, 0
        add vd, 1
        load ve, vd
        sub ve, vb
        skip.eq vf, 0
        jump __DIVMOD8_NO_SUB
        sub vd, vb
        add v0, 1
__DIVMOD8_NO_SUB:
        shr vc
        skip.eq vc, 0
        jump __DIVMOD8_LOOP
        ret
""")
            if self.needs_div:
                out.append("""__DIV8:
        call __DIVMOD8
        ret
""")
            if self.needs_mod:
                out.append("""__MOD8:
        call __DIVMOD8
        load v0, vd
        ret
""")

        return "\n".join(out)

    def compile_function(self, func_name, func_data, out):
        label = func_name.upper()
        out.append(f";;; Function: {func_name}")
        out.append(f"{label}:")

        # Local variable register allocation (v1..v9)
        # Scan for all local variable declarations and parameters
        locals_map = {}
        reg_avail = [f"v{i}" for i in range(1, 10)] # v1 through v9 reserved for locals
        reg_idx = 0

        for p in func_data["params"]:
            if reg_idx < len(reg_avail):
                locals_map[p] = reg_avail[reg_idx]
                reg_idx += 1

        self.collect_locals(func_data["body"], locals_map, reg_avail, reg_idx)

        ctx = {
            "func": func_name,
            "locals": locals_map,
            "out": out,
            "break_label": None,
            "continue_label": None
        }

        self.compile_statement(func_data["body"], ctx)

        out.append("        ret")
        out.append("")

    def collect_locals(self, stmt, locals_map, reg_avail, reg_idx):
        if not stmt: return reg_idx
        stype = stmt.get("type")
        if stype == "decl":
            var = stmt["var"]
            if var not in locals_map:
                if reg_idx < len(reg_avail):
                    locals_map[var] = reg_avail[reg_idx]
                    reg_idx += 1
                else:
                    raise ValueError(f"Too many local variables: '{var}' exceeds maximum {len(reg_avail)} registers (v1..v9)")
        elif stype == "block":
            for s in stmt["statements"]:
                reg_idx = self.collect_locals(s, locals_map, reg_avail, reg_idx)
        elif stype == "if":
            reg_idx = self.collect_locals(stmt["then"], locals_map, reg_avail, reg_idx)
            reg_idx = self.collect_locals(stmt.get("else"), locals_map, reg_avail, reg_idx)
        elif stype == "while":
            reg_idx = self.collect_locals(stmt["body"], locals_map, reg_avail, reg_idx)
        elif stype == "for":
            reg_idx = self.collect_locals(stmt.get("init"), locals_map, reg_avail, reg_idx)
            reg_idx = self.collect_locals(stmt["body"], locals_map, reg_avail, reg_idx)
        elif stype == "switch":
            for c in stmt["cases"]:
                for s in c["stmts"]:
                    reg_idx = self.collect_locals(s, locals_map, reg_avail, reg_idx)
        return reg_idx

    def compile_statement(self, stmt, ctx):
        if not stmt: return
        stype = stmt["type"]
        out = ctx["out"]

        if stype == "block":
            for s in stmt["statements"]:
                self.compile_statement(s, ctx)
        elif stype == "decl":
            var = stmt["var"]
            reg = ctx["locals"].get(var)
            if reg and stmt["init"]:
                self.compile_expr_into(stmt["init"], reg, ctx)
        elif stype == "expr":
            self.compile_expr(stmt["expr"], ctx)
        elif stype == "break":
            if ctx.get("break_label"):
                out.append(f"        jump {ctx['break_label']}")
        elif stype == "continue":
            if ctx.get("continue_label"):
                out.append(f"        jump {ctx['continue_label']}")
        elif stype == "return":
            if stmt["expr"]:
                self.compile_expr_into(stmt["expr"], "v0", ctx)
            out.append("        ret")
        elif stype == "if":
            lbl_else = self.new_label("IF_ELSE")
            lbl_end = self.new_label("IF_END")
            has_else = stmt.get("else") is not None

            # Compile condition: jumps to lbl_else if false
            self.compile_cond_branch(stmt["cond"], False, lbl_else, ctx)
            self.compile_statement(stmt["then"], ctx)
            if has_else:
                out.append(f"        jump {lbl_end}")
            out.append(f"{lbl_else}:")
            if has_else:
                self.compile_statement(stmt["else"], ctx)
                out.append(f"{lbl_end}:")
        elif stype == "while":
            lbl_start = self.new_label("WHILE_START")
            lbl_end = self.new_label("WHILE_END")
            old_break = ctx.get("break_label")
            old_cont = ctx.get("continue_label")
            ctx["break_label"] = lbl_end
            ctx["continue_label"] = lbl_start

            out.append(f"{lbl_start}:")
            # If condition is not literal '1' / 'true', test it
            cond = stmt["cond"]
            if not (cond.get("type") == "num" and cond.get("val") == 1):
                self.compile_cond_branch(cond, False, lbl_end, ctx)
            self.compile_statement(stmt["body"], ctx)
            out.append(f"        jump {lbl_start}")
            out.append(f"{lbl_end}:")
            ctx["break_label"] = old_break
            ctx["continue_label"] = old_cont
        elif stype == "for":
            lbl_start = self.new_label("FOR_START")
            lbl_step = self.new_label("FOR_STEP")
            lbl_end = self.new_label("FOR_END")
            old_break = ctx.get("break_label")
            old_cont = ctx.get("continue_label")
            ctx["break_label"] = lbl_end
            ctx["continue_label"] = lbl_step

            if stmt.get("init"):
                self.compile_statement(stmt["init"], ctx)
            out.append(f"{lbl_start}:")
            if stmt.get("cond"):
                self.compile_cond_branch(stmt["cond"], False, lbl_end, ctx)
            self.compile_statement(stmt["body"], ctx)
            out.append(f"{lbl_step}:")
            if stmt.get("post"):
                self.compile_expr(stmt["post"], ctx)
            out.append(f"        jump {lbl_start}")
            out.append(f"{lbl_end}:")
            ctx["break_label"] = old_break
            ctx["continue_label"] = old_cont
        elif stype == "switch":
            lbl_end = self.new_label("SWITCH_END")
            old_break = ctx["break_label"]
            ctx["break_label"] = lbl_end

            # Evaluate switch expression into temporary register va
            self.compile_expr_into(stmt["expr"], "va", ctx)

            case_labels = []
            default_label = None
            for c in stmt["cases"]:
                lbl_case = self.new_label("CASE")
                case_labels.append((c, lbl_case))
                if c["val"] == "default":
                    default_label = lbl_case

            # Emit jump table / comparisons
            for c, lbl_case in case_labels:
                if c["val"] != "default":
                    out.append(f"        skip.ne va, {c['val']}")
                    out.append(f"        jump {lbl_case}")

            if default_label:
                out.append(f"        jump {default_label}")
            else:
                out.append(f"        jump {lbl_end}")

            # Emit case bodies
            for c, lbl_case in case_labels:
                out.append(f"{lbl_case}:")
                for s in c["stmts"]:
                    self.compile_statement(s, ctx)

            out.append(f"{lbl_end}:")
            ctx["break_label"] = old_break

    # =========================================================================
    # Expressions & Conditionals
    # =========================================================================

    def compile_expr(self, expr, ctx):
        return self.compile_expr_into(expr, "v0", ctx)

    def compile_expr_into(self, expr, dest_reg, ctx):
        out = ctx["out"]
        etype = expr["type"]

        if etype == "num":
            out.append(f"        load {dest_reg}, {expr['val'] & 0xFF}")
            return dest_reg

        if etype == "ident":
            name = expr["name"]
            if name in ctx["locals"]:
                src_reg = ctx["locals"][name]
                if src_reg != dest_reg:
                    out.append(f"        load {dest_reg}, {src_reg}")
            elif name in self.globals:
                label = name.upper()
                out.append(f"        load i, {label}")
                out.append("        restore v0")
                if dest_reg != "v0":
                    out.append(f"        load {dest_reg}, v0")
            elif name in self.macros:
                val = int(eval(self.macros[name]))
                out.append(f"        load {dest_reg}, {val & 0xFF}")
            else:
                # Check for array / function label
                out.append(f"        load {dest_reg}, 0")
            return dest_reg

        if etype == "field":
            target = expr["target"]
            field = expr["field"]
            if target["type"] == "ident":
                var_name = target["name"]
                if var_name in self.globals and self.globals[var_name]["type"] == "struct":
                    st_name = self.globals[var_name]["struct_name"]
                    offset = self.struct_types[st_name]["fields"][field]["offset"]
                    label = var_name.upper()
                    loc_str = label if offset == 0 else f"{label} + {offset}"
                    out.append(f"        load i, {loc_str}")
                    out.append("        restore v0")
                    if dest_reg != "v0":
                        out.append(f"        load {dest_reg}, v0")
            return dest_reg

        if etype == "assign":
            target = expr["target"]
            op = expr["op"]
            # Compile right-hand side into dest_reg
            self.compile_expr_into(expr["value"], dest_reg, ctx)

            if target["type"] == "ident":
                name = target["name"]
                if name in ctx["locals"]:
                    var_reg = ctx["locals"][name]
                    if op == "=":
                        if var_reg != dest_reg:
                            out.append(f"        load {var_reg}, {dest_reg}")
                    elif op == "+=":
                        out.append(f"        add {var_reg}, {dest_reg}")
                    elif op == "-=":
                        out.append(f"        sub {var_reg}, {dest_reg}")
                    elif op == "&=":
                        out.append(f"        and {var_reg}, {dest_reg}")
                    elif op == "|=":
                        out.append(f"        or {var_reg}, {dest_reg}")
                    elif op == "^=":
                        out.append(f"        xor {var_reg}, {dest_reg}")
                elif name in self.globals:
                    label = name.upper()
                    if op == "=":
                        out.append(f"        load i, {label}")
                        out.append(f"        load v0, {dest_reg}")
                        out.append("        save v0")
                    else:
                        out.append(f"        load i, {label}")
                        out.append("        restore v0")
                        if op == "+=": out.append(f"        add v0, {dest_reg}")
                        elif op == "-=": out.append(f"        sub v0, {dest_reg}")
                        elif op == "&=": out.append(f"        and v0, {dest_reg}")
                        elif op == "|=": out.append(f"        or v0, {dest_reg}")
                        elif op == "^=": out.append(f"        xor v0, {dest_reg}")
                        out.append(f"        load i, {label}")
                        out.append("        save v0")
            elif target["type"] == "field":
                struct_target = target["target"]
                field = target["field"]
                if struct_target["type"] == "ident":
                    var_name = struct_target["name"]
                    if var_name in self.globals and self.globals[var_name]["type"] == "struct":
                        st_name = self.globals[var_name]["struct_name"]
                        offset = self.struct_types[st_name]["fields"][field]["offset"]
                        label = var_name.upper()
                        loc_str = label if offset == 0 else f"{label} + {offset}"
                        if op == "=":
                            out.append(f"        load i, {loc_str}")
                            out.append(f"        load v0, {dest_reg}")
                            out.append("        save v0")
                        else:
                            out.append(f"        load i, {loc_str}")
                            out.append("        restore v0")
                            if op == "+=": out.append(f"        add v0, {dest_reg}")
                            elif op == "-=": out.append(f"        sub v0, {dest_reg}")
                            elif op == "&=": out.append(f"        and v0, {dest_reg}")
                            elif op == "|=": out.append(f"        or v0, {dest_reg}")
                            elif op == "^=": out.append(f"        xor v0, {dest_reg}")
                            out.append(f"        load i, {loc_str}")
                            out.append("        save v0")
            elif target["type"] == "index":
                # Array assignment: arr[idx] = val
                arr_name = target["target"]["name"].upper()
                idx_expr = target["index"]
                self.compile_expr_into(idx_expr, "vc", ctx)
                out.append(f"        load i, {arr_name}")
                out.append("        add i, vc")
                out.append(f"        load v0, {dest_reg}")
                out.append("        save v0")
            return dest_reg

        if etype == "post_inc" or etype == "pre_inc":
            target = expr["target"]
            delta = 1 if expr["op"] == "++" else -1
            if target["type"] == "ident":
                name = target["name"]
                if name in ctx["locals"]:
                    reg = ctx["locals"][name]
                    if etype == "post_inc":
                        out.append(f"        load {dest_reg}, {reg}")
                    if delta == 1:
                        out.append(f"        add {reg}, 1")
                    else:
                        out.append(f"        sub {reg}, 1")
                    if etype == "pre_inc":
                        out.append(f"        load {dest_reg}, {reg}")
                elif name in self.globals:
                    label = name.upper()
                    out.append(f"        load i, {label}")
                    out.append("        restore v0")
                    if etype == "post_inc":
                        out.append(f"        load {dest_reg}, v0")
                    if delta == 1: out.append("        add v0, 1")
                    else: out.append("        sub v0, 1")
                    if etype == "pre_inc":
                        out.append(f"        load {dest_reg}, v0")
                    out.append(f"        load i, {label}")
                    out.append("        save v0")
            elif target["type"] == "field":
                struct_target = target["target"]
                field = target["field"]
                if struct_target["type"] == "ident":
                    var_name = struct_target["name"]
                    if var_name in self.globals and self.globals[var_name]["type"] == "struct":
                        st_name = self.globals[var_name]["struct_name"]
                        offset = self.struct_types[st_name]["fields"][field]["offset"]
                        label = var_name.upper()
                        loc_str = label if offset == 0 else f"{label} + {offset}"
                        out.append(f"        load i, {loc_str}")
                        out.append("        restore v0")
                        if etype == "post_inc":
                            out.append(f"        load {dest_reg}, v0")
                        if delta == 1: out.append("        add v0, 1")
                        else: out.append("        sub v0, 1")
                        if etype == "pre_inc":
                            out.append(f"        load {dest_reg}, v0")
                        out.append(f"        load i, {loc_str}")
                        out.append("        save v0")
            return dest_reg

        if etype == "index":
            # Read arr[idx]
            arr_name = expr["target"]["name"].upper()
            idx_expr = expr["index"]
            self.compile_expr_into(idx_expr, "vc", ctx)
            out.append(f"        load i, {arr_name}")
            out.append("        add i, vc")
            out.append("        restore v0")
            if dest_reg != "v0":
                out.append(f"        load {dest_reg}, v0")
            return dest_reg

        if etype == "call":
            return self.compile_call(expr, dest_reg, ctx)

        if etype == "binary":
            op = expr["op"]
            if op == "*":
                self.compile_expr_into(expr["left"], dest_reg, ctx)
                if expr["right"]["type"] == "num":
                    rv = expr["right"]["val"]
                    if rv == 0:
                        out.append(f"        load {dest_reg}, 0")
                    elif rv == 1:
                        pass
                    elif rv == 2:
                        out.append(f"        add {dest_reg}, {dest_reg}")
                    elif rv == 4:
                        out.append(f"        add {dest_reg}, {dest_reg}")
                        out.append(f"        add {dest_reg}, {dest_reg}")
                    elif rv == 8:
                        out.append(f"        add {dest_reg}, {dest_reg}")
                        out.append(f"        add {dest_reg}, {dest_reg}")
                        out.append(f"        add {dest_reg}, {dest_reg}")
                    elif rv == 16:
                        out.append(f"        add {dest_reg}, {dest_reg}")
                        out.append(f"        add {dest_reg}, {dest_reg}")
                        out.append(f"        add {dest_reg}, {dest_reg}")
                        out.append(f"        add {dest_reg}, {dest_reg}")
                    else:
                        self.needs_mul = True
                        out.append(f"        load va, {dest_reg}")
                        self.compile_expr_into(expr["right"], "vb", ctx)
                        out.append("        call __MUL8")
                        if dest_reg != "v0": out.append(f"        load {dest_reg}, v0")
                else:
                    self.needs_mul = True
                    out.append(f"        load va, {dest_reg}")
                    self.compile_expr_into(expr["right"], "vb", ctx)
                    out.append("        call __MUL8")
                    if dest_reg != "v0": out.append(f"        load {dest_reg}, v0")
                return dest_reg

            if op == "/":
                self.compile_expr_into(expr["left"], dest_reg, ctx)
                if expr["right"]["type"] == "num":
                    rv = expr["right"]["val"]
                    if rv == 1:
                        pass
                    elif rv in (2, 4, 8, 16):
                        shifts = {2: 1, 4: 2, 8: 3, 16: 4}[rv]
                        for _ in range(shifts):
                            out.append(f"        shr {dest_reg}")
                    else:
                        self.needs_div = True
                        out.append(f"        load va, {dest_reg}")
                        self.compile_expr_into(expr["right"], "vb", ctx)
                        out.append("        call __DIV8")
                        if dest_reg != "v0": out.append(f"        load {dest_reg}, v0")
                else:
                    self.needs_div = True
                    out.append(f"        load va, {dest_reg}")
                    self.compile_expr_into(expr["right"], "vb", ctx)
                    out.append("        call __DIV8")
                    if dest_reg != "v0": out.append(f"        load {dest_reg}, v0")
                return dest_reg

            if op == "%":
                self.compile_expr_into(expr["left"], dest_reg, ctx)
                if expr["right"]["type"] == "num":
                    rv = expr["right"]["val"]
                    if rv in (2, 4, 8, 16, 32, 64, 128):
                        out.append(f"        load vb, {rv - 1}")
                        out.append(f"        and {dest_reg}, vb")
                    else:
                        self.needs_mod = True
                        out.append(f"        load va, {dest_reg}")
                        self.compile_expr_into(expr["right"], "vb", ctx)
                        out.append("        call __MOD8")
                        if dest_reg != "v0": out.append(f"        load {dest_reg}, v0")
                else:
                    self.needs_mod = True
                    out.append(f"        load va, {dest_reg}")
                    self.compile_expr_into(expr["right"], "vb", ctx)
                    out.append("        call __MOD8")
                    if dest_reg != "v0": out.append(f"        load {dest_reg}, v0")
                return dest_reg

            if op == "<<":
                self.compile_expr_into(expr["left"], dest_reg, ctx)
                if expr["right"]["type"] == "num":
                    n = expr["right"]["val"] & 0x07
                    for _ in range(n):
                        out.append(f"        add {dest_reg}, {dest_reg}")
                else:
                    self.compile_expr_into(expr["right"], "vb", ctx)
                    lbl_loop = self.new_label("SHL_LOOP")
                    lbl_end = self.new_label("SHL_END")
                    out.append(f"        skip.ne vb, 0")
                    out.append(f"        jump {lbl_end}")
                    out.append(f"{lbl_loop}:")
                    out.append(f"        add {dest_reg}, {dest_reg}")
                    out.append(f"        sub vb, 1")
                    out.append(f"        skip.eq vb, 0")
                    out.append(f"        jump {lbl_loop}")
                    out.append(f"{lbl_end}:")
                return dest_reg

            if op == ">>":
                self.compile_expr_into(expr["left"], dest_reg, ctx)
                if expr["right"]["type"] == "num":
                    n = expr["right"]["val"] & 0x07
                    for _ in range(n):
                        out.append(f"        shr {dest_reg}")
                else:
                    self.compile_expr_into(expr["right"], "vb", ctx)
                    lbl_loop = self.new_label("SHR_LOOP")
                    lbl_end = self.new_label("SHR_END")
                    out.append(f"        skip.ne vb, 0")
                    out.append(f"        jump {lbl_end}")
                    out.append(f"{lbl_loop}:")
                    out.append(f"        shr {dest_reg}")
                    out.append(f"        sub vb, 1")
                    out.append(f"        skip.eq vb, 0")
                    out.append(f"        jump {lbl_loop}")
                    out.append(f"{lbl_end}:")
                return dest_reg

            if op == "+":
                self.compile_expr_into(expr["left"], dest_reg, ctx)
                if expr["right"]["type"] == "num":
                    rv = expr["right"]["val"] & 0xFF
                    if rv != 0:
                        out.append(f"        add {dest_reg}, {rv}")
                else:
                    self.compile_expr_into(expr["right"], "vb", ctx)
                    out.append(f"        add {dest_reg}, vb")
                return dest_reg

            if op == "&&":
                lbl_false = self.new_label("AND_FALSE")
                lbl_end = self.new_label("AND_END")
                self.compile_cond_branch(expr["left"], False, lbl_false, ctx)
                self.compile_cond_branch(expr["right"], False, lbl_false, ctx)
                out.append(f"        load {dest_reg}, 1")
                out.append(f"        jump {lbl_end}")
                out.append(f"{lbl_false}:")
                out.append(f"        load {dest_reg}, 0")
                out.append(f"{lbl_end}:")
                return dest_reg

            if op == "||":
                lbl_true = self.new_label("OR_TRUE")
                lbl_end = self.new_label("OR_END")
                self.compile_cond_branch(expr["left"], True, lbl_true, ctx)
                self.compile_cond_branch(expr["right"], True, lbl_true, ctx)
                out.append(f"        load {dest_reg}, 0")
                out.append(f"        jump {lbl_end}")
                out.append(f"{lbl_true}:")
                out.append(f"        load {dest_reg}, 1")
                out.append(f"{lbl_end}:")
                return dest_reg

            # Compile left into dest_reg
            self.compile_expr_into(expr["left"], dest_reg, ctx)
            # Compile right into temporary vb
            self.compile_expr_into(expr["right"], "vb", ctx)
            if op == "-": out.append(f"        sub {dest_reg}, vb")
            elif op == "&": out.append(f"        and {dest_reg}, vb")
            elif op == "|": out.append(f"        or {dest_reg}, vb")
            elif op == "^": out.append(f"        xor {dest_reg}, vb")
            elif op == "==":
                out.append(f"        load v0, 0")
                out.append(f"        skip.ne {dest_reg}, vb")
                out.append(f"        load v0, 1")
                if dest_reg != "v0": out.append(f"        load {dest_reg}, v0")
            elif op == "!=":
                out.append(f"        load v0, 0")
                out.append(f"        skip.eq {dest_reg}, vb")
                out.append(f"        load v0, 1")
                if dest_reg != "v0": out.append(f"        load {dest_reg}, v0")
            elif op == "<":
                out.append(f"        load ve, {dest_reg}")
                out.append("        sub ve, vb")
                out.append("        load v0, 1")
                out.append("        skip.eq vf, 0")
                out.append("        load v0, 0")
                if dest_reg != "v0": out.append(f"        load {dest_reg}, v0")
            elif op == "<=":
                out.append("        load ve, vb")
                out.append(f"        sub ve, {dest_reg}")
                out.append("        load v0, vf")
                if dest_reg != "v0": out.append(f"        load {dest_reg}, v0")
            elif op == ">":
                out.append("        load ve, vb")
                out.append(f"        sub ve, {dest_reg}")
                out.append("        load v0, 1")
                out.append("        skip.eq vf, 0")
                out.append("        load v0, 0")
                if dest_reg != "v0": out.append(f"        load {dest_reg}, v0")
            elif op == ">=":
                out.append(f"        load ve, {dest_reg}")
                out.append("        sub ve, vb")
                out.append("        load v0, vf")
                if dest_reg != "v0": out.append(f"        load {dest_reg}, v0")
            return dest_reg

        if etype == "unary":
            op = expr["op"]
            if op == "!":
                self.compile_expr_into(expr["expr"], "va", ctx)
                out.append(f"        load {dest_reg}, 0")
                out.append("        skip.ne va, 0")
                out.append(f"        load {dest_reg}, 1")
                return dest_reg
            elif op == "-":
                self.compile_expr_into(expr["expr"], "va", ctx)
                out.append(f"        load {dest_reg}, 0")
                out.append(f"        sub {dest_reg}, va")
                return dest_reg
            elif op == "~":
                self.compile_expr_into(expr["expr"], dest_reg, ctx)
                out.append("        load vb, 255")
                out.append(f"        xor {dest_reg}, vb")
                return dest_reg
            return dest_reg

        return dest_reg

    # =========================================================================
    # Conditional Branching
    # =========================================================================

    def compile_cond_branch(self, cond, jump_if_true, target_label, ctx):
        out = ctx["out"]
        ctype = cond["type"]

        if ctype == "unary" and cond.get("op") == "!":
            self.compile_cond_branch(cond["expr"], not jump_if_true, target_label, ctx)
            return

        if ctype == "binary" and cond["op"] == "&&":
            if jump_if_true:
                lbl_skip = self.new_label("AND_SKIP")
                self.compile_cond_branch(cond["left"], False, lbl_skip, ctx)
                self.compile_cond_branch(cond["right"], True, target_label, ctx)
                out.append(f"{lbl_skip}:")
            else:
                self.compile_cond_branch(cond["left"], False, target_label, ctx)
                self.compile_cond_branch(cond["right"], False, target_label, ctx)
            return

        if ctype == "binary" and cond["op"] == "||":
            if jump_if_true:
                self.compile_cond_branch(cond["left"], True, target_label, ctx)
                self.compile_cond_branch(cond["right"], True, target_label, ctx)
            else:
                lbl_skip = self.new_label("OR_SKIP")
                self.compile_cond_branch(cond["left"], True, lbl_skip, ctx)
                self.compile_cond_branch(cond["right"], False, target_label, ctx)
                out.append(f"{lbl_skip}:")
            return

        if ctype == "binary" and cond["op"] in ("==", "!=", "<", "<=", ">", ">="):
            op = cond["op"]
            left = cond["left"]
            right = cond["right"]

            # Optimize comparisons against constant numbers
            if right["type"] == "num":
                val = right["val"] & 0xFF
                if left["type"] == "ident" and left["name"] in ctx["locals"]:
                    reg = ctx["locals"][left["name"]]
                else:
                    self.compile_expr_into(left, "v0", ctx)
                    reg = "v0"

                if op == "==":
                    if jump_if_true:
                        out.append(f"        skip.ne {reg}, {val}")
                        out.append(f"        jump {target_label}")
                    else:
                        out.append(f"        skip.eq {reg}, {val}")
                        out.append(f"        jump {target_label}")
                    return
                elif op == "!=":
                    if jump_if_true:
                        out.append(f"        skip.eq {reg}, {val}")
                        out.append(f"        jump {target_label}")
                    else:
                        out.append(f"        skip.ne {reg}, {val}")
                        out.append(f"        jump {target_label}")
                    return

                elif op in ("<", "<=", ">", ">="):
                    out.append(f"        load vb, {val}")
                    if op == "<":
                        out.append(f"        load ve, {reg}")
                        out.append("        sub ve, vb")
                        skip_op = "skip.ne" if jump_if_true else "skip.eq"
                    elif op == ">=":
                        out.append(f"        load ve, {reg}")
                        out.append("        sub ve, vb")
                        skip_op = "skip.eq" if jump_if_true else "skip.ne"
                    elif op == "<=":
                        out.append("        load ve, vb")
                        out.append(f"        sub ve, {reg}")
                        skip_op = "skip.eq" if jump_if_true else "skip.ne"
                    else:  # >
                        out.append("        load ve, vb")
                        out.append(f"        sub ve, {reg}")
                        skip_op = "skip.ne" if jump_if_true else "skip.eq"
                    out.append(f"        {skip_op} vf, 0")
                    out.append(f"        jump {target_label}")
                    return

            # General comparison
            self.compile_expr_into(left, "va", ctx)
            self.compile_expr_into(right, "vb", ctx)

            if op == "==":
                if jump_if_true:
                    out.append(f"        skip.ne va, vb")
                    out.append(f"        jump {target_label}")
                else:
                    out.append(f"        skip.eq va, vb")
                    out.append(f"        jump {target_label}")
            elif op == "!=":
                if jump_if_true:
                    out.append(f"        skip.eq va, vb")
                    out.append(f"        jump {target_label}")
                else:
                    out.append(f"        skip.ne va, vb")
                    out.append(f"        jump {target_label}")
            elif op in ("<", "<=", ">", ">="):
                if op == "<":
                    out.append("        load ve, va")
                    out.append("        sub ve, vb")
                    skip_op = "skip.ne" if jump_if_true else "skip.eq"
                elif op == ">=":
                    out.append("        load ve, va")
                    out.append("        sub ve, vb")
                    skip_op = "skip.eq" if jump_if_true else "skip.ne"
                elif op == "<=":
                    out.append("        load ve, vb")
                    out.append("        sub ve, va")
                    skip_op = "skip.eq" if jump_if_true else "skip.ne"
                else:  # >
                    out.append("        load ve, vb")
                    out.append("        sub ve, va")
                    skip_op = "skip.ne" if jump_if_true else "skip.eq"
                out.append(f"        {skip_op} vf, 0")
                out.append(f"        jump {target_label}")
            return

        # General boolean condition: non-zero = true, zero = false
        self.compile_expr_into(cond, "v0", ctx)
        if jump_if_true:
            out.append(f"        skip.eq v0, 0")
            out.append(f"        jump {target_label}")
        else:
            out.append(f"        skip.ne v0, 0")
            out.append(f"        jump {target_label}")

    # =========================================================================
    # Function Calls & Flashiibo SDK Mappings
    # =========================================================================

    def is_simple_arg(self, arg, target_reg, ctx):
        if not arg:
            return True
        t = arg.get("type")
        if t == "num":
            return True
        if t == "ident":
            name = arg["name"]
            loc = ctx.get("locals", {}).get(name)
            if loc:
                if target_reg not in ctx.get("locals", {}).values():
                    return True
                if loc == target_reg:
                    return True
        return False

    def compile_call_args(self, args, target_regs, ctx):
        out = ctx["out"]
        depth = ctx.get("call_depth", 0)
        eval_ctx = dict(ctx)
        eval_ctx["call_depth"] = depth + 1

        saved_indices = set()
        for i, (arg, target_reg) in enumerate(zip(args, target_regs)):
            if not self.is_simple_arg(arg, target_reg, ctx):
                saved_indices.add(i)
                self.compile_expr_into(arg, "v0", eval_ctx)
                buf_name = f"__ARG_{depth}_{i}"
                self.call_arg_buffers.add(buf_name)
                out.append(f"        load i, {buf_name}")
                out.append("        save v0")

        for i, (arg, target_reg) in enumerate(zip(args, target_regs)):
            if i in saved_indices:
                buf_name = f"__ARG_{depth}_{i}"
                out.append(f"        load i, {buf_name}")
                out.append("        restore v0")
                if target_reg != "v0":
                    out.append(f"        load {target_reg}, v0")
            else:
                self.compile_expr_into(arg, target_reg, ctx)

    def compile_call(self, call_node, dest_reg, ctx):
        out = ctx["out"]
        func_name = call_node["func"]["name"]
        args = call_node["args"]

        # ---------------------------------------------------------------------
        # Flashiibo FEB SDK Built-in APIs
        # ---------------------------------------------------------------------
        if func_name in ("feb_set_high_res", "feb_set_hires"):
            # feb_set_high_res(bool enable)
            if args and args[0].get("val") == 0:
                out.append("        low")
            else:
                out.append("        high")
            return dest_reg

        if func_name in ("feb_exit", "feb_quit"):
            out.append("        exit")
            return dest_reg

        if func_name == "feb_clear_screen":
            out.append("        cls")
            return dest_reg

        if func_name == "feb_wait_key":
            out.append(f"        load {dest_reg}, key")
            return dest_reg

        if func_name in ("feb_get_keys", "feb_read_buttons"):
            out.append(f"        getkeys {dest_reg}")
            return dest_reg

        if func_name in ("feb_set_delay_timer", "feb_set_delay"):
            self.compile_call_args([args[0]], ["v0"], ctx)
            out.append("        load dt, v0")
            return dest_reg

        if func_name in ("feb_get_delay_timer", "feb_get_delay"):
            out.append(f"        load {dest_reg}, dt")
            return dest_reg

        if func_name in ("feb_delay_frames", "feb_sleep"):
            self.compile_call_args([args[0]], ["v0"], ctx)
            lbl_loop = self.new_label("DELAY_LOOP")
            out.append("        load dt, v0")
            out.append(f"{lbl_loop}:")
            out.append("        load v0, dt")
            out.append("        skip.eq v0, 0")
            out.append(f"        jump {lbl_loop}")
            return dest_reg

        if func_name == "feb_draw_sprite":
            # feb_draw_sprite(x, y, sprite, height) or (x, y, height, sprite)
            self.compile_call_args([args[0], args[1]], ["va", "vb"], ctx)
            if args[2].get("type") == "ident":
                sprite_label = args[2]["name"].upper()
                h = args[3]["val"] if len(args) > 3 and args[3].get("type") == "num" else 8
            else:
                sprite_label = args[3]["name"].upper() if len(args) > 3 and "name" in args[3] else "SPRITE"
                h = args[2]["val"] if args[2].get("type") == "num" else 8
            out.append(f"        load i, {sprite_label}")
            out.append(f"        draw va, vb, {h}")
            if dest_reg != "vf":
                out.append(f"        load {dest_reg}, vf")
            return dest_reg

        if func_name == "feb_draw_sprite16":
            # feb_draw_sprite16(x, y, sprite)
            self.compile_call_args([args[0], args[1]], ["va", "vb"], ctx)
            if args[2]["type"] == "ident":
                name = args[2]["name"]
                sprite_label = name.upper()
                out.append(f"        load i, {sprite_label}")
            out.append("        draw va, vb, 0")
            if dest_reg != "vf":
                out.append(f"        load {dest_reg}, vf")
            return dest_reg

        if func_name in ("feb_draw_digit", "feb_draw_num"):
            # feb_draw_digit(x, y, digit)
            self.compile_call_args([args[0], args[1], args[2]], ["va", "vb", "vc"], ctx)
            out.append("        hex vc")
            out.append("        draw va, vb, 5")
            return dest_reg

        if func_name == "feb_set_draw_mode":
            self.compile_call_args([args[0]], ["va"], ctx)
            out.append("        drawmode va")
            return dest_reg

        if func_name == "feb_draw_pixel":
            self.compile_call_args([args[0], args[1]], ["va", "vb"], ctx)
            out.append("        pixel va")
            return dest_reg

        if func_name == "feb_draw_line":
            self.compile_call_args([args[0], args[1], args[2], args[3]], ["va", "vb", "vc", "vd"], ctx)
            out.append("        line va")
            return dest_reg

        if func_name == "feb_draw_hline":
            self.compile_call_args([args[0], args[1], args[2]], ["va", "vb", "vc"], ctx)
            out.append("        hline va")
            return dest_reg

        if func_name == "feb_draw_vline":
            self.compile_call_args([args[0], args[1], args[2]], ["va", "vb", "vc"], ctx)
            out.append("        vline va")
            return dest_reg

        if func_name == "feb_draw_rect":
            self.compile_call_args([args[0], args[1], args[2], args[3]], ["va", "vb", "vc", "vd"], ctx)
            out.append("        rect va")
            return dest_reg

        if func_name == "feb_fill_rect":
            self.compile_call_args([args[0], args[1], args[2], args[3]], ["va", "vb", "vc", "vd"], ctx)
            out.append("        fillrect va")
            return dest_reg

        if func_name == "feb_draw_circle":
            self.compile_call_args([args[0], args[1], args[2]], ["va", "vb", "vc"], ctx)
            out.append("        circle va")
            return dest_reg

        if func_name == "feb_fill_circle":
            self.compile_call_args([args[0], args[1], args[2]], ["va", "vb", "vc"], ctx)
            out.append("        disc va")
            return dest_reg

        if func_name == "feb_test_pixel":
            self.compile_call_args([args[0], args[1]], ["va", "vb"], ctx)
            out.append("        testpixel va")
            if dest_reg != "vf":
                out.append(f"        load {dest_reg}, vf")
            return dest_reg

        if func_name in ("feb_draw_string", "feb_draw_text"):
            # feb_draw_string(x, y, str, font)
            self.compile_call_args([args[0], args[1], args[3]], ["va", "vb", "vc"], ctx)
            # String label
            if args[2]["type"] == "str":
                str_lbl = args[2]["label"]
                out.append(f"        load i, {str_lbl}")
            elif args[2]["type"] == "ident":
                str_lbl = args[2]["name"].upper()
                out.append(f"        load i, {str_lbl}")
            out.append("        text va")
            if dest_reg != "va":
                out.append(f"        load {dest_reg}, va")
            return dest_reg

        if func_name in ("feb_draw_char", "feb_draw_character"):
            # feb_draw_char(x, y, ch, font)
            self.compile_call_args([args[0], args[1], args[2], args[3]], ["va", "vb", "vc", "vd"], ctx)
            out.append("        char va")
            if dest_reg != "va":
                out.append(f"        load {dest_reg}, va")
            return dest_reg

        if func_name in ("feb_string_width", "feb_str_width"):
            # feb_string_width(str, font)
            self.compile_call_args([args[1]], ["va"], ctx)
            if args[0]["type"] == "str":
                str_lbl = args[0]["label"]
                out.append(f"        load i, {str_lbl}")
            elif args[0]["type"] == "ident":
                str_lbl = args[0]["name"].upper()
                out.append(f"        load i, {str_lbl}")
            out.append("        textlen va")
            if dest_reg != "va":
                out.append(f"        load {dest_reg}, va")
            return dest_reg

        if func_name == "feb_draw_number":
            # feb_draw_number(x, y, num, font)
            self.compile_call_args([args[0], args[1], args[2], args[3]], ["va", "vb", "vd", "vc"], ctx)
            if args[2]["type"] == "num":
                out.append(f"        load i, {args[2]['val'] & 0xFFF}")
            else:
                out.append("        load i, 0")
                out.append("        add i, vd")
            out.append("        num va")
            if dest_reg != "va":
                out.append(f"        load {dest_reg}, va")
            return dest_reg

        if func_name == "feb_rand":
            mask = args[0]["val"] if args[0]["type"] == "num" else 0xFF
            out.append(f"        rnd {dest_reg}, {mask & 0xFF}")
            return dest_reg

        if func_name == "feb_save_flags":
            # feb_save_flags(data, len) or feb_save_flags(path, data, len)
            len_val = args[-1]["val"] if args[-1]["type"] == "num" else 1
            first_arg = args[1] if len(args) == 3 else args[0]
            if first_arg["type"] == "addrof":
                target = first_arg["target"]
                if target["type"] == "ident":
                    var_name = target["name"]
                    if var_name in ctx["locals"]:
                        reg = ctx["locals"][var_name]
                        out.append(f"        load v0, {reg}")
                    elif var_name in self.globals:
                        out.append(f"        load i, {var_name.upper()}")
                        out.append("        restore v0")
                elif target["type"] == "field":
                    st_target = target["target"]
                    st_field = target["field"]
                    if st_target["type"] == "ident":
                        var_name = st_target["name"]
                        if var_name in self.globals and self.globals[var_name]["type"] == "struct":
                            st_name = self.globals[var_name]["struct_name"]
                            offset = self.struct_types[st_name]["fields"][st_field]["offset"]
                            label = var_name.upper()
                            loc_str = label if offset == 0 else f"{label} + {offset}"
                            out.append(f"        load i, {loc_str}")
                            out.append("        restore v0")
            out.append("        saveflags v0")
            return dest_reg

        if func_name == "feb_load_flags":
            len_val = args[-1]["val"] if args[-1]["type"] == "num" else 1
            first_arg = args[1] if len(args) == 3 else args[0]
            out.append("        loadflags v0")
            if first_arg["type"] == "addrof":
                target = first_arg["target"]
                if target["type"] == "ident":
                    var_name = target["name"]
                    if var_name in ctx["locals"]:
                        reg = ctx["locals"][var_name]
                        out.append(f"        load {reg}, v0")
                    elif var_name in self.globals:
                        out.append(f"        load i, {var_name.upper()}")
                        out.append("        save v0")
                elif target["type"] == "field":
                    st_target = target["target"]
                    st_field = target["field"]
                    if st_target["type"] == "ident":
                        var_name = st_target["name"]
                        if var_name in self.globals and self.globals[var_name]["type"] == "struct":
                            st_name = self.globals[var_name]["struct_name"]
                            offset = self.struct_types[st_name]["fields"][st_field]["offset"]
                            label = var_name.upper()
                            loc_str = label if offset == 0 else f"{label} + {offset}"
                            out.append(f"        load i, {loc_str}")
                            out.append("        save v0")
            return dest_reg

        # ---------------------------------------------------------------------
        # User-Defined Function Call
        # ---------------------------------------------------------------------
        target_func = func_name.upper()
        caller = ctx.get("func")
        has_frame = bool(caller and ctx.get("locals"))
        if has_frame:
            self.frame_buffers.add(caller)
            frame_lbl = f"FRAME_{caller.upper()}"
            out.append(f"        load i, {frame_lbl}")
            out.append("        save v9")

        # Compile arguments into v1, v2, v3...
        arg_regs = [f"v{i}" for i in range(1, len(args) + 1)]
        self.compile_call_args(args, arg_regs, ctx)

        out.append(f"        call {target_func}")
        if has_frame:
            out.append("        load ve, v0")
            out.append(f"        load i, {frame_lbl}")
            out.append("        restore v9")
            out.append("        load v0, ve")

        if dest_reg != "v0":
            out.append(f"        load {dest_reg}, v0")
        return dest_reg

